draw_self()
draw_set_valign(fa_middle)
draw_text(x + 16 * image_xscale, y + 16, potency)
draw_set_valign(fa_top)
draw_sprite_ext(effec, cad_formula, host.x, host.y, host.image_xscale, 1, 0, c_white, effec_alpha)